"""qc materials and crucible qc variant

Revision ID: 1d81304e5265
Revises: e8b58da4cd75
Create Date: 2026-08-25 03:47:13.658977
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1d81304e5265"
down_revision: str | None = "e8b58da4cd75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qc_material",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "qc_type",
            sa.Enum(
                "crm",
                "blank",
                "coarse_blank",
                "field_duplicate",
                "prep_duplicate",
                "pulp_duplicate",
                name="qc_material_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("lot_number", sa.String(length=100), nullable=True),
        sa.Column("certified_au_value_g_t", sa.Numeric(), nullable=True),
        sa.Column("certified_au_uncertainty_g_t", sa.Numeric(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "certified_au_uncertainty_g_t IS NULL OR certified_au_uncertainty_g_t > 0",
            name=op.f("ck_qc_material_certified_au_uncertainty_positive"),
        ),
        sa.CheckConstraint(
            "certified_au_value_g_t IS NULL OR certified_au_value_g_t >= 0",
            name=op.f("ck_qc_material_certified_au_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qc_material")),
        sa.UniqueConstraint("name", name=op.f("uq_qc_material_name")),
    )
    op.create_index(op.f("ix_qc_material_created_at"), "qc_material", ["created_at"], unique=False)
    op.create_index(op.f("ix_qc_material_qc_type"), "qc_material", ["qc_type"], unique=False)
    op.add_column("crucible", sa.Column("qc_material_id", sa.BigInteger(), nullable=True))
    op.alter_column("crucible", "sample_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_index(
        op.f("ix_crucible_qc_material_id"), "crucible", ["qc_material_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_crucible_qc_material_id_qc_material"),
        "crucible",
        "qc_material",
        ["qc_material_id"],
        ["id"],
    )
    op.create_check_constraint(
        op.f("ck_crucible_exactly_one_of_sample_and_qc_material"),
        "crucible",
        "(sample_id IS NOT NULL) <> (qc_material_id IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_crucible_exactly_one_of_sample_and_qc_material"), "crucible", type_="check"
    )
    op.drop_constraint(
        op.f("fk_crucible_qc_material_id_qc_material"), "crucible", type_="foreignkey"
    )
    op.drop_index(op.f("ix_crucible_qc_material_id"), table_name="crucible")
    op.alter_column("crucible", "sample_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("crucible", "qc_material_id")
    op.drop_index(op.f("ix_qc_material_qc_type"), table_name="qc_material")
    op.drop_index(op.f("ix_qc_material_created_at"), table_name="qc_material")
    op.drop_table("qc_material")
    # ### end Alembic commands ###
