"""initial schema

Revision ID: 7172b2adeb7e
Revises:
Create Date: 2026-08-22 21:23:30.658446
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7172b2adeb7e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_person", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("code", name=op.f("uq_client_code")),
        sa.UniqueConstraint("name", name=op.f("uq_client_name")),
    )
    op.create_index(op.f("ix_client_created_at"), "client", ["created_at"], unique=False)
    op.create_table(
        "instrument",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "instrument_type",
            sa.Enum(
                "aas",
                "icp_ms",
                "icp_oes",
                "xrf",
                "microbalance",
                "crusher",
                "pulverizer",
                "furnace",
                name="instrument_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "maintenance",
                "out_of_service",
                "retired",
                name="instrument_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("calibration_due_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
        sa.UniqueConstraint("name", name=op.f("uq_instrument_name")),
    )
    op.create_index(op.f("ix_instrument_created_at"), "instrument", ["created_at"], unique=False)
    op.create_table(
        "lab_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "prep_tech",
                "analyst",
                "supervisor",
                "lab_manager",
                "client",
                name="role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_user")),
        sa.UniqueConstraint("email", name=op.f("uq_lab_user_email")),
        sa.UniqueConstraint("subject", name=op.f("uq_lab_user_subject")),
    )
    op.create_index(op.f("ix_lab_user_created_at"), "lab_user", ["created_at"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_project_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_project_client_id_client")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("client_id", "name", name="client_name"),
    )
    op.create_index(op.f("ix_project_client_id"), "project", ["client_id"], unique=False)
    op.create_index(op.f("ix_project_created_at"), "project", ["created_at"], unique=False)
    op.create_table(
        "drill_hole",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("hole_id", sa.String(length=50), nullable=False),
        sa.Column("easting", sa.Numeric(), nullable=True),
        sa.Column("northing", sa.Numeric(), nullable=True),
        sa.Column("elevation_m", sa.Numeric(), nullable=True),
        sa.Column("utm_zone", sa.String(length=8), nullable=True),
        sa.Column("total_depth_m", sa.Numeric(), nullable=True),
        sa.Column("dip_degrees", sa.Numeric(), nullable=True),
        sa.Column("azimuth_degrees", sa.Numeric(), nullable=True),
        sa.Column("drilling_method", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "azimuth_degrees IS NULL OR azimuth_degrees >= 0 AND azimuth_degrees < 360",
            name=op.f("ck_drill_hole_azimuth_range"),
        ),
        sa.CheckConstraint(
            "dip_degrees IS NULL OR dip_degrees BETWEEN -90 AND 90",
            name=op.f("ck_drill_hole_dip_range"),
        ),
        sa.CheckConstraint(
            "total_depth_m IS NULL OR total_depth_m > 0", name=op.f("ck_drill_hole_depth_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_drill_hole_project_id_project")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drill_hole")),
        sa.UniqueConstraint("project_id", "hole_id", name="project_hole"),
    )
    op.create_index(op.f("ix_drill_hole_created_at"), "drill_hole", ["created_at"], unique=False)
    op.create_index(op.f("ix_drill_hole_project_id"), "drill_hole", ["project_id"], unique=False)
    op.create_table(
        "submission",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("submission_number", sa.String(length=30), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.Column("client_reference", sa.String(length=100), nullable=True),
        sa.Column("purchase_order", sa.String(length=100), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_by_id", sa.BigInteger(), nullable=True),
        sa.Column("declared_sample_count", sa.Integer(), nullable=True),
        sa.Column("rush", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("requested_tat_days", sa.Integer(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "declared_sample_count IS NULL OR declared_sample_count >= 0",
            name=op.f("ck_submission_declared_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_submission_client_id_client")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("fk_submission_project_id_project")
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"], ["lab_user.id"], name=op.f("fk_submission_received_by_id_lab_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission")),
        sa.UniqueConstraint("submission_number", name="number"),
    )
    op.create_index(op.f("ix_submission_client_id"), "submission", ["client_id"], unique=False)
    op.create_index(op.f("ix_submission_created_at"), "submission", ["created_at"], unique=False)
    op.create_index(op.f("ix_submission_project_id"), "submission", ["project_id"], unique=False)
    op.create_table(
        "sample",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.String(length=100), nullable=False),
        sa.Column("submission_id", sa.BigInteger(), nullable=False),
        sa.Column("drill_hole_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "sample_type",
            sa.Enum(
                "core",
                "rc_chip",
                "soil",
                "stream_sediment",
                "rock_chip",
                "pulp",
                name="sample_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "in_prep",
                "ready_for_assay",
                "in_assay",
                "assayed",
                "reported",
                "rejected",
                name="sample_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("from_depth_m", sa.Numeric(), nullable=True),
        sa.Column("to_depth_m", sa.Numeric(), nullable=True),
        sa.Column("easting", sa.Numeric(), nullable=True),
        sa.Column("northing", sa.Numeric(), nullable=True),
        sa.Column("elevation_m", sa.Numeric(), nullable=True),
        sa.Column("lithology_code", sa.String(length=20), nullable=True),
        sa.Column("alteration_code", sa.String(length=20), nullable=True),
        sa.Column("weight_received_g", sa.Numeric(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(from_depth_m IS NULL) = (to_depth_m IS NULL)", name=op.f("ck_sample_depths_together")
        ),
        sa.CheckConstraint(
            "drill_hole_id IS NOT NULL OR from_depth_m IS NULL",
            name=op.f("ck_sample_interval_requires_hole"),
        ),
        sa.CheckConstraint(
            "from_depth_m IS NULL OR (from_depth_m >= 0 AND to_depth_m > from_depth_m)",
            name=op.f("ck_sample_interval_advances"),
        ),
        sa.CheckConstraint(
            "weight_received_g IS NULL OR weight_received_g > 0",
            name=op.f("ck_sample_received_weight_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["drill_hole_id"], ["drill_hole.id"], name=op.f("fk_sample_drill_hole_id_drill_hole")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submission.id"], name=op.f("fk_sample_submission_id_submission")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample")),
        sa.UniqueConstraint("sample_id", name="label"),
    )
    op.create_index(op.f("ix_sample_created_at"), "sample", ["created_at"], unique=False)
    op.create_index(op.f("ix_sample_drill_hole_id"), "sample", ["drill_hole_id"], unique=False)
    op.create_index(
        "ix_sample_hole_interval", "sample", ["drill_hole_id", "from_depth_m"], unique=False
    )
    op.create_index(op.f("ix_sample_status"), "sample", ["status"], unique=False)
    op.create_index(op.f("ix_sample_submission_id"), "sample", ["submission_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sample_submission_id"), table_name="sample")
    op.drop_index(op.f("ix_sample_status"), table_name="sample")
    op.drop_index("ix_sample_hole_interval", table_name="sample")
    op.drop_index(op.f("ix_sample_drill_hole_id"), table_name="sample")
    op.drop_index(op.f("ix_sample_created_at"), table_name="sample")
    op.drop_table("sample")
    op.drop_index(op.f("ix_submission_project_id"), table_name="submission")
    op.drop_index(op.f("ix_submission_created_at"), table_name="submission")
    op.drop_index(op.f("ix_submission_client_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("ix_drill_hole_project_id"), table_name="drill_hole")
    op.drop_index(op.f("ix_drill_hole_created_at"), table_name="drill_hole")
    op.drop_table("drill_hole")
    op.drop_index(op.f("ix_project_created_at"), table_name="project")
    op.drop_index(op.f("ix_project_client_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_lab_user_created_at"), table_name="lab_user")
    op.drop_table("lab_user")
    op.drop_index(op.f("ix_instrument_created_at"), table_name="instrument")
    op.drop_table("instrument")
    op.drop_index(op.f("ix_client_created_at"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###
