"""audit event

Revision ID: a64c168cff52
Revises: 7172b2adeb7e
Create Date: 2026-08-22 21:24:13.071484
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a64c168cff52"
down_revision: str | None = "7172b2adeb7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.String(length=63), nullable=False),
        sa.Column("record_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "action <> 'amend' OR (reason IS NOT NULL AND length(trim(reason)) > 0)",
            name=op.f("ck_audit_event_amendment_states_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["lab_user.id"], name=op.f("fk_audit_event_actor_id_lab_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(op.f("ix_audit_event_actor_id"), "audit_event", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_event_created_at"), "audit_event", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_event_target", "audit_event", ["table_name", "record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_event_target", table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_created_at"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_actor_id"), table_name="audit_event")
    op.drop_table("audit_event")
    # ### end Alembic commands ###
