"""crucible parting and weighing measurements

Revision ID: e8b58da4cd75
Revises: cfef85e840d4
Create Date: 2026-08-25 03:15:46.196666
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e8b58da4cd75"
down_revision: str | None = "cfef85e840d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crucible", sa.Column("lead_button_weight_mg", sa.Numeric(), nullable=True))
    op.add_column("crucible", sa.Column("prill_weight_mg", sa.Numeric(), nullable=True))
    op.add_column("crucible", sa.Column("parting_acid_volume_ml", sa.Numeric(), nullable=True))
    op.add_column("crucible", sa.Column("parted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("crucible", sa.Column("gold_bead_mg", sa.Numeric(), nullable=True))
    op.add_column("crucible", sa.Column("weighed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        op.f("ck_crucible_gold_bead_non_negative"), "crucible", "gold_bead_mg >= 0"
    )
    op.create_check_constraint(
        op.f("ck_crucible_lead_button_weight_positive"),
        "crucible",
        "lead_button_weight_mg > 0",
    )
    op.create_check_constraint(
        op.f("ck_crucible_parting_acid_volume_positive"),
        "crucible",
        "parting_acid_volume_ml > 0",
    )
    op.create_check_constraint(
        op.f("ck_crucible_prill_weight_positive"), "crucible", "prill_weight_mg > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_crucible_prill_weight_positive"), "crucible", type_="check")
    op.drop_constraint(op.f("ck_crucible_parting_acid_volume_positive"), "crucible", type_="check")
    op.drop_constraint(op.f("ck_crucible_lead_button_weight_positive"), "crucible", type_="check")
    op.drop_constraint(op.f("ck_crucible_gold_bead_non_negative"), "crucible", type_="check")
    op.drop_column("crucible", "weighed_at")
    op.drop_column("crucible", "gold_bead_mg")
    op.drop_column("crucible", "parted_at")
    op.drop_column("crucible", "parting_acid_volume_ml")
    op.drop_column("crucible", "prill_weight_mg")
    op.drop_column("crucible", "lead_button_weight_mg")
    # ### end Alembic commands ###
