"""certificate

Revision ID: f73c45982855
Revises: 9a1c2e6f4b3d
Create Date: 2026-08-24 17:27:39.599994
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f73c45982855"
down_revision: str | None = "9a1c2e6f4b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("certificate_number", sa.String(length=30), nullable=False),
        sa.Column("client_id", sa.BigInteger(), nullable=False),
        sa.Column("issued_by_id", sa.BigInteger(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supersedes_id", sa.BigInteger(), nullable=True),
        sa.Column("superseded_reason", sa.Text(), nullable=True),
        sa.Column("pdf_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR (superseded_reason IS NOT NULL AND length(trim(superseded_reason)) > 0)",
            name=op.f("ck_certificate_supersession_states_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_certificate_client_id_client")
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_id"], ["lab_user.id"], name=op.f("fk_certificate_issued_by_id_lab_user")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["certificate.id"],
            name=op.f("fk_certificate_supersedes_id_certificate"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificate")),
        sa.UniqueConstraint("certificate_number", name=op.f("uq_certificate_certificate_number")),
    )
    op.create_index(op.f("ix_certificate_client_id"), "certificate", ["client_id"], unique=False)
    op.create_index(op.f("ix_certificate_created_at"), "certificate", ["created_at"], unique=False)
    op.create_table(
        "certificate_result",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("certificate_id", sa.BigInteger(), nullable=False),
        sa.Column("sample_id", sa.BigInteger(), nullable=False),
        sa.Column("fire_assay_result_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificate.id"],
            name=op.f("fk_certificate_result_certificate_id_certificate"),
        ),
        sa.ForeignKeyConstraint(
            ["fire_assay_result_id"],
            ["fire_assay_result.id"],
            name=op.f("fk_certificate_result_fire_assay_result_id_fire_assay_result"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"], ["sample.id"], name=op.f("fk_certificate_result_sample_id_sample")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificate_result")),
        sa.UniqueConstraint("certificate_id", "sample_id", name="certificate_sample"),
    )
    op.create_index(
        op.f("ix_certificate_result_certificate_id"),
        "certificate_result",
        ["certificate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_certificate_result_created_at"), "certificate_result", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_certificate_result_sample_id"), "certificate_result", ["sample_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_certificate_result_sample_id"), table_name="certificate_result")
    op.drop_index(op.f("ix_certificate_result_created_at"), table_name="certificate_result")
    op.drop_index(op.f("ix_certificate_result_certificate_id"), table_name="certificate_result")
    op.drop_table("certificate_result")
    op.drop_index(op.f("ix_certificate_created_at"), table_name="certificate")
    op.drop_index(op.f("ix_certificate_client_id"), table_name="certificate")
    op.drop_table("certificate")
    # ### end Alembic commands ###
