"""furnace batching

Revision ID: f9845a996c0d
Revises: 2d5f8a17c930
Create Date: 2026-08-25 01:29:18.557184
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f9845a996c0d"
down_revision: str | None = "2d5f8a17c930"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flux_recipe",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "matrix_type",
            sa.Enum(
                "silicate",
                "sulfide",
                "oxide",
                "carbonate",
                "carbonaceous",
                name="matrix_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("nominal_portion_g", sa.Numeric(), nullable=False),
        sa.Column("litharge_g", sa.Numeric(), nullable=False),
        sa.Column("soda_ash_g", sa.Numeric(), nullable=False),
        sa.Column("borax_g", sa.Numeric(), nullable=False),
        sa.Column("silica_g", sa.Numeric(), nullable=False),
        sa.Column("flour_g", sa.Numeric(), nullable=False),
        sa.Column("nitre_g", sa.Numeric(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("borax_g >= 0", name=op.f("ck_flux_recipe_borax_non_negative")),
        sa.CheckConstraint("flour_g >= 0", name=op.f("ck_flux_recipe_flour_non_negative")),
        sa.CheckConstraint("litharge_g >= 0", name=op.f("ck_flux_recipe_litharge_non_negative")),
        sa.CheckConstraint("nitre_g >= 0", name=op.f("ck_flux_recipe_nitre_non_negative")),
        sa.CheckConstraint(
            "nominal_portion_g > 0", name=op.f("ck_flux_recipe_nominal_portion_positive")
        ),
        sa.CheckConstraint("silica_g >= 0", name=op.f("ck_flux_recipe_silica_non_negative")),
        sa.CheckConstraint("soda_ash_g >= 0", name=op.f("ck_flux_recipe_soda_ash_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flux_recipe")),
        sa.UniqueConstraint("name", name=op.f("uq_flux_recipe_name")),
    )
    op.create_index(op.f("ix_flux_recipe_created_at"), "flux_recipe", ["created_at"], unique=False)
    op.create_table(
        "batch",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_number", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "charging",
                "in_fusion",
                "fused",
                "in_cupellation",
                "cupelled",
                "completed",
                name="batch_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("opened_by_id", sa.BigInteger(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["opened_by_id"], ["lab_user.id"], name=op.f("fk_batch_opened_by_id_lab_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch")),
        sa.UniqueConstraint("batch_number", name=op.f("uq_batch_batch_number")),
    )
    op.create_index(op.f("ix_batch_created_at"), "batch", ["created_at"], unique=False)
    op.create_index(op.f("ix_batch_status"), "batch", ["status"], unique=False)
    op.create_table(
        "crucible",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("sample_id", sa.BigInteger(), nullable=False),
        sa.Column("flux_recipe_id", sa.BigInteger(), nullable=False),
        sa.Column("position_row", sa.Integer(), nullable=False),
        sa.Column("position_col", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "empty",
                "charged",
                "fused",
                "cupelled",
                "parted",
                "weighed",
                "rejected",
                name="crucible_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sample_weight_g", sa.Numeric(), nullable=False),
        sa.Column("litharge_g", sa.Numeric(), nullable=False),
        sa.Column("soda_ash_g", sa.Numeric(), nullable=False),
        sa.Column("borax_g", sa.Numeric(), nullable=False),
        sa.Column("silica_g", sa.Numeric(), nullable=False),
        sa.Column("flour_g", sa.Numeric(), nullable=False),
        sa.Column("nitre_g", sa.Numeric(), nullable=False),
        sa.Column("charged_by_id", sa.BigInteger(), nullable=False),
        sa.Column("charged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("position_col > 0", name=op.f("ck_crucible_position_col_positive")),
        sa.CheckConstraint("position_row > 0", name=op.f("ck_crucible_position_row_positive")),
        sa.CheckConstraint("sample_weight_g > 0", name=op.f("ck_crucible_sample_weight_positive")),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batch.id"], name=op.f("fk_crucible_batch_id_batch")
        ),
        sa.ForeignKeyConstraint(
            ["charged_by_id"], ["lab_user.id"], name=op.f("fk_crucible_charged_by_id_lab_user")
        ),
        sa.ForeignKeyConstraint(
            ["flux_recipe_id"],
            ["flux_recipe.id"],
            name=op.f("fk_crucible_flux_recipe_id_flux_recipe"),
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"], ["sample.id"], name=op.f("fk_crucible_sample_id_sample")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crucible")),
        sa.UniqueConstraint("batch_id", "position_row", "position_col", name="batch_position"),
        sa.UniqueConstraint("batch_id", "sample_id", name="batch_sample"),
    )
    op.create_index(op.f("ix_crucible_batch_id"), "crucible", ["batch_id"], unique=False)
    op.create_index(op.f("ix_crucible_created_at"), "crucible", ["created_at"], unique=False)
    op.create_index(op.f("ix_crucible_sample_id"), "crucible", ["sample_id"], unique=False)
    op.create_index(op.f("ix_crucible_status"), "crucible", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crucible_status"), table_name="crucible")
    op.drop_index(op.f("ix_crucible_sample_id"), table_name="crucible")
    op.drop_index(op.f("ix_crucible_created_at"), table_name="crucible")
    op.drop_index(op.f("ix_crucible_batch_id"), table_name="crucible")
    op.drop_table("crucible")
    op.drop_index(op.f("ix_batch_status"), table_name="batch")
    op.drop_index(op.f("ix_batch_created_at"), table_name="batch")
    op.drop_table("batch")
    op.drop_index(op.f("ix_flux_recipe_created_at"), table_name="flux_recipe")
    op.drop_table("flux_recipe")
    # ### end Alembic commands ###
