/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Clients
         * @description List all clients, newest first, with submission count.
         *
         *     Lean rows like ``GET /api/samples``: just enough to populate a filter
         *     dropdown or a client-management table, no per-row deep lookup.
         */
        get: operations["read_clients_api_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drill-holes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Drill Hole */
        post: operations["create_drill_hole_api_drill_holes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fire-assay-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fire Assay Result */
        post: operations["create_fire_assay_result_api_fire_assay_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fire-assay-results/solution-finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Solution Finish */
        post: operations["create_solution_finish_api_fire_assay_results_solution_finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Certificate */
        post: operations["create_certificate_api_certificates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Certificate */
        get: operations["read_certificate_api_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the signed Certificate of Analysis */
        get: operations["download_certificate_pdf_api_certificates__certificate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Samples */
        get: operations["read_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Sample */
        get: operations["read_sample_api_samples__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Sample Provenance
         * @description This sample's whole evidence dossier — audit idea #3.
         *
         *     Assembled read-only from rows that already existed and sealed with a
         *     `sha256` a recipient can recompute offline. Nested under the sample
         *     rather than given its own top-level path because a dossier is not an
         *     entity in its own right: it is one view of one sample, the same way
         *     `/api/certificates/{id}/pdf` is one rendering of one certificate.
         */
        get: operations["read_sample_provenance_api_samples__sample_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance Sample Status */
        patch: operations["advance_sample_status_api_samples__sample_id__status_patch"];
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Submission
         * @description Register a work order and the sample rows that arrived with it.
         *
         *     ``actor`` and ``received_by`` are resolved from the same request and
         *     normally agree, but the role check reads ``actor.role`` — never
         *     ``received_by.role`` — so authorisation always reflects what the current
         *     caller holds right now, not whatever :class:`~msa_lims.db.models.LabUser`
         *     row last recorded.
         */
        post: operations["create_submission_api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flux-recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Flux Recipes */
        get: operations["read_flux_recipes_api_flux_recipes_get"];
        put?: never;
        /** Create Flux Recipe */
        post: operations["create_flux_recipe_api_flux_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Batches */
        get: operations["read_batches_api_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Charge Crucible */
        post: operations["charge_crucible_api_batches__batch_id__crucibles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles/{crucible_id}/parting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Crucible Parting */
        post: operations["record_crucible_parting_api_batches__batch_id__crucibles__crucible_id__parting_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles/{crucible_id}/weighing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Crucible Weighing */
        post: operations["record_crucible_weighing_api_batches__batch_id__crucibles__crucible_id__weighing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance Batch Status */
        patch: operations["advance_batch_status_api_batches__batch_id__status_patch"];
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Batch */
        get: operations["read_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/qc-dossier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Batch Qc Dossier
         * @description This completed batch's sealed QC dossier — audit idea #5's contract.
         *
         *     Nested under the batch like parting and weighing: a dossier is one view
         *     of one batch, not an entity of its own. Generation is idempotent and
         *     content-addressed; fetching twice without new measurements returns the
         *     same seal and writes nothing new (see `qc_dossiers/service.py`). The
         *     threshold flags are advisory — recording that a blank came back above the
         *     lab's line; judging what that means is QC Sentinel's job.
         */
        get: operations["read_batch_qc_dossier_api_batches__batch_id__qc_dossier_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qc-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Qc Materials */
        get: operations["read_qc_materials_api_qc_materials_get"];
        put?: never;
        /** Create Qc Material */
        post: operations["create_qc_material_api_qc_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Audit Chain Verification */
        get: operations["read_audit_chain_verification_api_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}/multi-element-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Multi Element Results
         * @description Read the current (un-superseded) element results for a sample.
         */
        get: operations["list_multi_element_results_api_samples__sample_id__multi_element_results_get"];
        put?: never;
        /**
         * Import Multi Element Results
         * @description Bulk-import one ICP run's worth of element results for a sample.
         *
         *     The request carries the sample id both in the URL and in the body — the
         *     URL is the RESTful anchor, the body is what the service reads — and the
         *     two must agree.
         */
        post: operations["import_multi_element_results_api_samples__sample_id__multi_element_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditChainVerificationOut */
        AuditChainVerificationOut: {
            /** Valid */
            valid: boolean;
            /** Verified Count */
            verified_count: number;
            /** Head Hash */
            head_hash: string | null;
            /** Broke At Id */
            broke_at_id: number | null;
            /** Broke Reason */
            broke_reason: string | null;
        };
        /** BatchCreate */
        BatchCreate: {
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Notes */
            notes?: string | null;
        };
        /** BatchDetailOut */
        BatchDetailOut: {
            /** Id */
            id: number;
            /** Batch Number */
            batch_number: string;
            /** Status */
            status: string;
            /** Opened By Id */
            opened_by_id: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Notes */
            notes: string | null;
            /** Furnace Rows */
            furnace_rows: number;
            /** Furnace Columns */
            furnace_columns: number;
            /** Crucibles */
            crucibles: components["schemas"]["CrucibleSlotOut"][];
        };
        /** BatchOut */
        BatchOut: {
            /** Id */
            id: number;
            /** Batch Number */
            batch_number: string;
            /** Status */
            status: string;
            /** Opened By Id */
            opened_by_id: number;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Notes */
            notes: string | null;
        };
        /**
         * BatchStatus
         * @description Where a fire assay batch is in the furnace cycle.
         *
         *     These are physical states of a tray of crucibles, not workflow conveniences:
         *     once a batch is InFusion it is inside a 1000 °C furnace and nothing about it
         *     can be edited.
         * @enum {string}
         */
        BatchStatus: "pending" | "charging" | "in_fusion" | "fused" | "in_cupellation" | "cupelled" | "completed";
        /** BatchStatusUpdate */
        BatchStatusUpdate: {
            status: components["schemas"]["BatchStatus"];
        };
        /** CertificateCreate */
        CertificateCreate: {
            /** Client Id */
            client_id: number;
            /** Sample Ids */
            sample_ids: number[];
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Notes */
            notes?: string | null;
            /**
             * Supersedes Id
             * @description Set to amend an existing certificate.
             */
            supersedes_id?: number | null;
            /**
             * Superseded Reason
             * @description Required when supersedes_id is set.
             */
            superseded_reason?: string | null;
        };
        /** CertificateOut */
        CertificateOut: {
            /** Id */
            id: number;
            /** Certificate Number */
            certificate_number: string;
            /** Client Id */
            client_id: number;
            /** Issued By Id */
            issued_by_id: number;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Superseded Reason */
            superseded_reason: string | null;
            /** Notes */
            notes: string | null;
            /** Samples */
            samples: components["schemas"]["CertifiedSampleOut"][];
        };
        /**
         * CertificateReferenceOut
         * @description One certificate that names a sample — not the whole document, just
         *     enough to link to it via ``GET /api/certificates/{id}``.
         */
        CertificateReferenceOut: {
            /** Id */
            id: number;
            /** Certificate Number */
            certificate_number: string;
        };
        /**
         * CertifiedElementOut
         * @description One element reading frozen into a certificate.
         */
        CertifiedElementOut: {
            /** Element */
            element: string;
            /** Grade Value */
            grade_value: string;
            /** Grade Unit */
            grade_unit: string;
            /** Detection Limit */
            detection_limit: string | null;
            /** Digest Method */
            digest_method: string;
        };
        /**
         * CertifiedSampleOut
         * @description One sample a certificate covers, and the specific result it certified —
         *     see ``certificates/service.py``'s ``CertifiedSampleInfo`` for why this is
         *     the frozen-at-issuance result, not necessarily the sample's current one.
         */
        CertifiedSampleOut: {
            /** Sample Id */
            sample_id: number;
            /** Sample Label */
            sample_label: string;
            /** Fire Assay Result Id */
            fire_assay_result_id: number;
            /** Method */
            method: string;
            au: components["schemas"]["MeasuredValueOut"];
            /**
             * Elements
             * @default []
             */
            elements: components["schemas"]["CertifiedElementOut"][];
            /** Digest Method */
            digest_method?: string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /**
             * Code
             * @description e.g. 'MSA'
             */
            code: string;
            /** Name */
            name: string;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Billing Address */
            billing_address?: string | null;
        };
        /**
         * ClientListItemOut
         * @description Lean client row for listing — code, name, and submission count.
         */
        ClientListItemOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            /** Submission Count */
            submission_count: number;
        };
        /** ClientOut */
        ClientOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Contact Person */
            contact_person: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Billing Address */
            billing_address: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable" | "not_configured";
            /** Detail */
            detail?: string | null;
        };
        /** CrucibleChargeCreate */
        CrucibleChargeCreate: {
            /** Sample Id */
            sample_id?: number | null;
            /** Qc Material Id */
            qc_material_id?: number | null;
            /** Insertion Type */
            insertion_type?: ("field_duplicate" | "prep_duplicate" | "pulp_duplicate") | null;
            /** Flux Recipe Id */
            flux_recipe_id: number;
            /** Position Row */
            position_row: number;
            /** Position Col */
            position_col: number;
            /** Sample Weight G */
            sample_weight_g: number | string;
            /**
             * Charged At
             * Format: date-time
             */
            charged_at: string;
            /** Notes */
            notes?: string | null;
        };
        /** CrucibleOut */
        CrucibleOut: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Sample Id */
            sample_id: number | null;
            /** Qc Material Id */
            qc_material_id: number | null;
            /** Insertion Type */
            insertion_type: string | null;
            /** Flux Recipe Id */
            flux_recipe_id: number;
            /** Position Row */
            position_row: number;
            /** Position Col */
            position_col: number;
            /** Status */
            status: string;
            /** Sample Weight G */
            sample_weight_g: string;
            /** Litharge G */
            litharge_g: string;
            /** Soda Ash G */
            soda_ash_g: string;
            /** Borax G */
            borax_g: string;
            /** Silica G */
            silica_g: string;
            /** Flour G */
            flour_g: string;
            /** Nitre G */
            nitre_g: string;
            /** Lead Button Weight Mg */
            lead_button_weight_mg: string | null;
            /** Prill Weight Mg */
            prill_weight_mg: string | null;
            /** Parting Acid Volume Ml */
            parting_acid_volume_ml: string | null;
            /** Parted At */
            parted_at: string | null;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            /** Weighed At */
            weighed_at: string | null;
            /**
             * Charged At
             * Format: date-time
             */
            charged_at: string;
            /** Notes */
            notes: string | null;
        };
        /**
         * CruciblePartingCreate
         * @description The measurements taken while parting one cupelled crucible.
         */
        CruciblePartingCreate: {
            /**
             * Lead Button Weight Mg
             * @description Lead button from the fusion.
             */
            lead_button_weight_mg: number | string;
            /**
             * Prill Weight Mg
             * @description Doré bead left by cupellation.
             */
            prill_weight_mg: number | string;
            /**
             * Parting Acid Volume Ml
             * @description Acid used to part the prill.
             */
            parting_acid_volume_ml: number | string;
            /**
             * Parted At
             * Format: date-time
             * @description When the parting happened, not when it was entered.
             */
            parted_at: string;
        };
        /**
         * CrucibleSlotOut
         * @description One crucible as it appears in a batch's tray — lean, unlike
         *     `CrucibleOut`: a grid of up to 36 of these needs a position, a status to
         *     colour it, and whatever it holds' label, not every flux amount and
         *     measurement column. That fuller detail is one click away at the sample
         *     it names; nothing here needs its own crucible-detail endpoint yet.
         */
        CrucibleSlotOut: {
            /** Id */
            id: number;
            /** Position Row */
            position_row: number;
            /** Position Col */
            position_col: number;
            /** Status */
            status: string;
            /** Sample Id */
            sample_id: number | null;
            /** Sample Label */
            sample_label: string | null;
            /** Qc Material Id */
            qc_material_id: number | null;
            /** Qc Material Name */
            qc_material_name: string | null;
            /** Qc Material Type */
            qc_material_type: string | null;
            /** Insertion Type */
            insertion_type: string | null;
        };
        /**
         * CrucibleWeighingCreate
         * @description The final gold-bead weighing for one parted crucible.
         */
        CrucibleWeighingCreate: {
            /**
             * Gold Bead Mg
             * @description Gold alone, after parting.
             */
            gold_bead_mg: number | string;
            /**
             * Weighed At
             * Format: date-time
             * @description When the weighing happened, not when entered.
             */
            weighed_at: string;
        };
        /** DrillHoleCreate */
        DrillHoleCreate: {
            /** Project Id */
            project_id: number;
            /**
             * Hole Id
             * @description e.g. 'MSA-24-001'
             */
            hole_id: string;
            /** Easting */
            easting?: number | string | null;
            /** Northing */
            northing?: number | string | null;
            /** Elevation M */
            elevation_m?: number | string | null;
            /** Utm Zone */
            utm_zone?: string | null;
            /** Total Depth M */
            total_depth_m?: number | string | null;
            /** Dip Degrees */
            dip_degrees?: number | string | null;
            /** Azimuth Degrees */
            azimuth_degrees?: number | string | null;
            /** Drilling Method */
            drilling_method?: string | null;
        };
        /** DrillHoleOut */
        DrillHoleOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Hole Id */
            hole_id: string;
            /** Easting */
            easting: string | null;
            /** Northing */
            northing: string | null;
            /** Elevation M */
            elevation_m: string | null;
            /** Utm Zone */
            utm_zone: string | null;
            /** Total Depth M */
            total_depth_m: string | null;
            /** Dip Degrees */
            dip_degrees: string | null;
            /** Azimuth Degrees */
            azimuth_degrees: string | null;
            /** Drilling Method */
            drilling_method: string | null;
        };
        /**
         * ElementResultCreate
         * @description One element's grade from an ICP run, as entered by the analyst.
         */
        ElementResultCreate: {
            /**
             * Element
             * @description IUPAC symbol — the same label the instrument export uses (e.g. 'Au', 'Cu').
             */
            element: string;
            /**
             * Grade Value
             * @description Grade in the solid sample, in grade_unit.
             */
            grade_value: number | string;
            /**
             * Grade Unit
             * @description Mass-fraction unit of the grade.
             * @default ppm
             * @enum {string}
             */
            grade_unit: "ppm" | "ppb" | "g/t" | "%";
            /**
             * Detection Limit
             * @description Method detection limit, in grade_unit.
             */
            detection_limit?: number | string | null;
        };
        /** FireAssayResultCreate */
        FireAssayResultCreate: {
            /** Sample Id */
            sample_id: number;
            /**
             * Gold Bead Mg
             * @description Bead weight after parting — gold alone. Required unless crucible_id names a crucible that has been weighed; then its recorded bead is used and this must be left unset.
             */
            gold_bead_mg?: number | string | null;
            /**
             * Sample Weight G
             * @description The portion assayed. Required unless crucible_id names the crucible the sample was charged into — then its recorded charge is used and this must be left unset.
             */
            sample_weight_g?: number | string | null;
            /** Balance Sensitivity Mg */
            balance_sensitivity_mg?: number | string | null;
            /**
             * Dore Bead Mg
             * @description Doré bead weight (Au + Ag) before parting. When supplied alongside gold_bead_mg, silver by difference is computed and stored.
             */
            dore_bead_mg?: number | string | null;
            /**
             * Analysed At
             * Format: date-time
             * @description When the weighing happened, not when it was entered.
             */
            analysed_at: string;
            /** Notes */
            notes?: string | null;
            /**
             * Supersedes Id
             * @description Set to correct an existing result.
             */
            supersedes_id?: number | null;
            /**
             * Superseded Reason
             * @description Required when supersedes_id is set.
             */
            superseded_reason?: string | null;
            /**
             * Crucible Id
             * @description The crucible this assay came from; its recorded charge is derived as the portion weight.
             */
            crucible_id?: number | null;
        };
        /**
         * FireAssayResultOut
         * @description One result of either finish.
         *
         *     The finish-specific fields are nullable on the way out for the same reason
         *     they are nullable in the table: a gravimetric row has no concentration and
         *     a solution row has no bead. ``method`` says which set to expect, and ``au``
         *     — the grade, the thing every consumer actually wants — is present and
         *     identically shaped on both.
         *
         *     Silver is nullable: it is computed only when both doré and gold bead
         *     weights are present (gravimetric finish), and is absent on a solution
         *     finish or when the lab did not supply a doré weight.
         */
        FireAssayResultOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: number;
            /** Method */
            method: string;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            /** Sample Weight G */
            sample_weight_g: string;
            /** Balance Sensitivity Mg */
            balance_sensitivity_mg: string | null;
            /** Solution Concentration */
            solution_concentration: string | null;
            /** Solution Concentration Unit */
            solution_concentration_unit: string | null;
            /** Solution Volume Ml */
            solution_volume_ml: string | null;
            /** Solution Detection Limit */
            solution_detection_limit: string | null;
            au: components["schemas"]["MeasuredValueOut"];
            silver: components["schemas"]["MeasuredValueOut"] | null;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Superseded Reason */
            superseded_reason: string | null;
            /** Notes */
            notes: string | null;
            /** Crucible Id */
            crucible_id: number | null;
        };
        /** FluxRecipeCreate */
        FluxRecipeCreate: {
            /**
             * Name
             * @description e.g. 'Standard Silicate'
             */
            name: string;
            matrix_type: components["schemas"]["MatrixType"];
            /**
             * Nominal Portion G
             * @description Sample weight this recipe's amounts are calibrated for.
             */
            nominal_portion_g: number | string;
            /** Litharge G */
            litharge_g: number | string;
            /** Soda Ash G */
            soda_ash_g: number | string;
            /** Borax G */
            borax_g: number | string;
            /** Silica G */
            silica_g: number | string;
            /** Flour G */
            flour_g: number | string;
            /** Nitre G */
            nitre_g: number | string;
        };
        /** FluxRecipeOut */
        FluxRecipeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Matrix Type */
            matrix_type: string;
            /** Nominal Portion G */
            nominal_portion_g: string;
            /** Litharge G */
            litharge_g: string;
            /** Soda Ash G */
            soda_ash_g: string;
            /** Borax G */
            borax_g: string;
            /** Silica G */
            silica_g: string;
            /** Flour G */
            flour_g: string;
            /** Nitre G */
            nitre_g: string;
            /** Is Active */
            is_active: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** Version */
            version: string;
            database: components["schemas"]["ComponentHealth"];
            qc_sentinel: components["schemas"]["ComponentHealth"];
        };
        /**
         * MatrixType
         * @description The mineralogical character of a sample charge — what it is made of,
         *     for the purpose of choosing a flux.
         *
         *     Independent of :class:`SampleType`, which classifies the physical medium
         *     a sample arrived as (core, soil, pulp, ...). A silicate-hosted soil and a
         *     silicate-hosted core take the same flux; a sulfide-rich core and an
         *     oxide-rich core do not, despite both being "core." Nothing in this schema
         *     infers a matrix from a sample type or a lithology code — a technician
         *     assigns it when charging a crucible, the same way they would read it off
         *     a geologist's log.
         * @enum {string}
         */
        MatrixType: "silicate" | "sulfide" | "oxide" | "carbonate" | "carbonaceous";
        /**
         * MeasuredValueOut
         * @description Mirrors ``frontend/src/types.ts``'s ``MeasuredValue`` exactly, so the
         *     same ``formatMeasured`` helper renders a non-detect correctly the moment
         *     a screen exists to show one — a censored value is never a null string
         *     quietly standing in for zero.
         */
        MeasuredValueOut: {
            /** Value */
            value: string | null;
            /** Detection Limit */
            detection_limit: string | null;
            /** Censored */
            censored: boolean;
            /** Unit */
            unit: string;
        };
        /**
         * MultiElementImportCreate
         * @description Bulk import of one ICP run's worth of elements for a sample.
         *
         *     The endpoint accepts the whole run at once rather than one element at a
         *     time: an instrument exports dozens of elements per sample, and a partial
         *     write would leave the sample with half its elements assayed.
         */
        MultiElementImportCreate: {
            /** Sample Id */
            sample_id: number;
            /**
             * Digest Method
             * @description How the sample was taken into solution. The certificate must name the digest: aqua regia is partial, four-acid is total.
             * @enum {string}
             */
            digest_method: "aqua_regia" | "four_acid" | "peroxide_fusion";
            /**
             * Method Notes
             * @description Free-text notes about the digest or instrument setup.
             */
            method_notes?: string | null;
            /**
             * Analysed At
             * Format: date-time
             * @description When the instrument read it, not when it was entered.
             */
            analysed_at: string;
            /**
             * Results
             * @description 30-50 elements typical; at least one required.
             */
            results: components["schemas"]["ElementResultCreate"][];
        };
        /**
         * MultiElementImportOut
         * @description The result of a bulk import: the rows created and audit events.
         */
        MultiElementImportOut: {
            /** Sample Id */
            sample_id: number;
            /** Digest Method */
            digest_method: string;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Imported */
            imported: components["schemas"]["MultiElementResultOut"][];
        };
        /**
         * MultiElementResultOut
         * @description One element's stored result, on the way out.
         */
        MultiElementResultOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: number;
            /** Element */
            element: string;
            /** Grade Value */
            grade_value: string;
            /** Grade Unit */
            grade_unit: string;
            /** Detection Limit */
            detection_limit: string | null;
            /** Digest Method */
            digest_method: string;
            /** Method Notes */
            method_notes: string | null;
            /** Analyst Id */
            analyst_id: number;
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Superseded Reason */
            superseded_reason: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Client Id */
            client_id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Client Id */
            client_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Location */
            location: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
        };
        /** ProvenanceAuditEntryOut */
        ProvenanceAuditEntryOut: {
            /** Id */
            id: number;
            /** Table Name */
            table_name: string;
            /** Record Id */
            record_id: number;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string | null;
            /** Actor */
            actor: string | null;
            /** Recorded At */
            recorded_at: string | null;
            /** Entry Hash */
            entry_hash: string;
        };
        /** ProvenanceCertificateOut */
        ProvenanceCertificateOut: {
            /** Id */
            id: number;
            /** Certificate Number */
            certificate_number: string;
            /** Issued At */
            issued_at: string | null;
            /** Issued By */
            issued_by: string | null;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Certified Result Id */
            certified_result_id: number;
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Superseded Reason */
            superseded_reason: string | null;
        };
        /** ProvenanceClientOut */
        ProvenanceClientOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
        };
        /** ProvenanceCrucibleOut */
        ProvenanceCrucibleOut: {
            /** Id */
            id: number;
            /** Batch Number */
            batch_number: string;
            /** Position */
            position: string;
            /** Status */
            status: string;
            /** Flux Recipe */
            flux_recipe: string;
            /** Sample Weight G */
            sample_weight_g: string | null;
            /** Charged At */
            charged_at: string | null;
            /** Lead Button Weight Mg */
            lead_button_weight_mg: string | null;
            /** Prill Weight Mg */
            prill_weight_mg: string | null;
            /** Parting Acid Volume Ml */
            parting_acid_volume_ml: string | null;
            /** Parted At */
            parted_at: string | null;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            /** Weighed At */
            weighed_at: string | null;
        };
        /** ProvenanceDrillHoleOut */
        ProvenanceDrillHoleOut: {
            /** Hole Id */
            hole_id: string;
        };
        /**
         * ProvenanceOut
         * @description One sample's whole evidence dossier, plus the seal over it.
         *
         *     Every value is rendered as a string where it is a `Decimal` or a
         *     timestamp in the database — the seal is computed over exactly these
         *     bytes, so a float or a re-formatted date here would make an
         *     independently recomputed seal disagree for no reason a reader could
         *     see. See `provenance/service.py`.
         */
        ProvenanceOut: {
            sample: components["schemas"]["ProvenanceSampleOut"];
            submission: components["schemas"]["ProvenanceSubmissionOut"];
            client: components["schemas"]["ProvenanceClientOut"];
            project: components["schemas"]["ProvenanceProjectOut"] | null;
            drill_hole: components["schemas"]["ProvenanceDrillHoleOut"] | null;
            /** Crucibles */
            crucibles: components["schemas"]["ProvenanceCrucibleOut"][];
            /** Results */
            results: components["schemas"]["ProvenanceResultOut"][];
            /** Certificates */
            certificates: components["schemas"]["ProvenanceCertificateOut"][];
            /** Audit Entries */
            audit_entries: components["schemas"]["ProvenanceAuditEntryOut"][];
            /** Seal */
            seal: string;
        };
        /** ProvenanceProjectOut */
        ProvenanceProjectOut: {
            /** Name */
            name: string;
        };
        /** ProvenanceResultOut */
        ProvenanceResultOut: {
            /** Id */
            id: number;
            /** Method */
            method: string;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            /** Sample Weight G */
            sample_weight_g: string | null;
            /** Au Value */
            au_value: string | null;
            /** Au Detection Limit */
            au_detection_limit: string | null;
            /** Au Censored */
            au_censored: boolean;
            /** Au Unit */
            au_unit: string;
            /** Analysed At */
            analysed_at: string | null;
            /** Analyst */
            analyst: string | null;
            /** Crucible Id */
            crucible_id: number | null;
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Superseded Reason */
            superseded_reason: string | null;
        };
        /** ProvenanceSampleOut */
        ProvenanceSampleOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** From Depth M */
            from_depth_m: string | null;
            /** To Depth M */
            to_depth_m: string | null;
            /** Weight Received G */
            weight_received_g: string | null;
        };
        /** ProvenanceSubmissionOut */
        ProvenanceSubmissionOut: {
            /** Id */
            id: number;
            /** Submission Number */
            submission_number: string;
            /** Received At */
            received_at: string | null;
            /** Received By */
            received_by: string | null;
            /** Client Reference */
            client_reference: string | null;
        };
        /**
         * QcAdvisoryOut
         * @description One advisory observation — a flag, never a verdict (see
         *     `domain/qc.py`).
         */
        QcAdvisoryOut: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /**
         * QcAuOut
         * @description The reconstructed grade, shaped exactly like every other rendering of
         *     a `MeasuredValue` on the wire.
         */
        QcAuOut: {
            /** Value */
            value: string;
            /** Detection Limit */
            detection_limit: string | null;
            /** Censored */
            censored: boolean;
            /** Unit */
            unit: string;
        };
        /** QcAuPair */
        QcAuPair: {
            /** Value */
            value: string;
            /** Detection Limit */
            detection_limit: string | null;
            /** Censored */
            censored: boolean;
            /** Unit */
            unit: string;
        };
        /** QcBatchRef */
        QcBatchRef: {
            /** Id */
            id: number;
            /** Batch Number */
            batch_number: string;
        };
        /**
         * QcDossierOut
         * @description One completed batch's sealed QC dossier, plus the seal over it.
         *
         *     Every value is rendered as a string where it is a `Decimal` in the
         *     database — the seal is computed over exactly these bytes, so a float here
         *     would make an independently recomputed seal disagree for no reason a
         *     reader could see. See `qc_dossiers/service.py`.
         */
        QcDossierOut: {
            batch: components["schemas"]["QcBatchRef"];
            /** Entries */
            entries: components["schemas"]["QcEntryOut"][];
            /** Duplicates */
            duplicates: components["schemas"]["QcDuplicateOut"][];
            /** Batch Flags */
            batch_flags: components["schemas"]["QcAdvisoryOut"][];
            /** Seal */
            seal: string;
        };
        /** QcDuplicateOut */
        QcDuplicateOut: {
            sample: components["schemas"]["QcSampleRef"];
            /** Insertion Type */
            insertion_type: string;
            /** Position */
            position: string;
            /** Crucible Status */
            crucible_status: string;
            /** Portion G */
            portion_g: string;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            au: components["schemas"]["QcAuPair"] | null;
            original_au: components["schemas"]["QcAuPair"] | null;
            stats: components["schemas"]["QcDuplicateStatsOut"] | null;
            /** Advisories */
            advisories: components["schemas"]["QcAdvisoryOut"][];
        };
        /**
         * QcDuplicateStatsOut
         * @description The canonical pair statistics: RPD plus the Thompson–Howarth (x, y)
         *     point — mean against absolute difference.
         */
        QcDuplicateStatsOut: {
            /** Mean G T */
            mean_g_t: string;
            /** Abs Diff G T */
            abs_diff_g_t: string;
            /** Rpd Percent */
            rpd_percent: string;
        };
        /** QcEntryOut */
        QcEntryOut: {
            material: components["schemas"]["QcMaterialRef"];
            /** Position */
            position: string;
            /** Crucible Status */
            crucible_status: string;
            /** Portion G */
            portion_g: string;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            au: components["schemas"]["QcAuOut"] | null;
            /** Certified Au Value G T */
            certified_au_value_g_t: string | null;
            /** Certified Au Uncertainty G T */
            certified_au_uncertainty_g_t: string | null;
            /** Z Score */
            z_score: string | null;
            /** Advisories */
            advisories: components["schemas"]["QcAdvisoryOut"][];
        };
        /** QcMaterialCreate */
        QcMaterialCreate: {
            /**
             * Name
             * @description e.g. 'OREAS 501d'
             */
            name: string;
            qc_type: components["schemas"]["QcMaterialType"];
            /** Lot Number */
            lot_number?: string | null;
            /** Certified Au Value G T */
            certified_au_value_g_t?: number | string | null;
            /** Certified Au Uncertainty G T */
            certified_au_uncertainty_g_t?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** QcMaterialOut */
        QcMaterialOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Qc Type */
            qc_type: string;
            /** Lot Number */
            lot_number: string | null;
            /** Certified Au Value G T */
            certified_au_value_g_t: string | null;
            /** Certified Au Uncertainty G T */
            certified_au_uncertainty_g_t: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** QcMaterialRef */
        QcMaterialRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Qc Type */
            qc_type: string;
            /** Lot Number */
            lot_number: string | null;
        };
        /**
         * QcMaterialType
         * @description What kind of control was inserted into a batch.
         *
         *     The LIMS records the *insertion* — which material went into which position.
         *     Judging the result is QC Sentinel's job; there is deliberately no verdict
         *     vocabulary in this system.
         * @enum {string}
         */
        QcMaterialType: "crm" | "blank" | "coarse_blank" | "field_duplicate" | "prep_duplicate" | "pulp_duplicate";
        /** QcSampleRef */
        QcSampleRef: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** SampleCreate */
        SampleCreate: {
            /**
             * Sample Id
             * @description e.g. 'MSA-24-001-142.50_144.00' (drill) or 'MSA-24-SO-00417' (surface)
             */
            sample_id: string;
            sample_type: components["schemas"]["SampleType"];
            /** Lithology Code */
            lithology_code?: string | null;
            /** Alteration Code */
            alteration_code?: string | null;
            /** Weight Received G */
            weight_received_g?: number | string | null;
            /** Easting */
            easting?: number | string | null;
            /** Northing */
            northing?: number | string | null;
            /** Elevation M */
            elevation_m?: number | string | null;
            /** Comments */
            comments?: string | null;
        };
        /** SampleDetailOut */
        SampleDetailOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** Submission Id */
            submission_id: number;
            /** Drill Hole Id */
            drill_hole_id: number | null;
            /** From Depth M */
            from_depth_m: string | null;
            /** To Depth M */
            to_depth_m: string | null;
            current_result: components["schemas"]["FireAssayResultOut"] | null;
            /** Certificates */
            certificates: components["schemas"]["CertificateReferenceOut"][];
        };
        /**
         * SampleListItemOut
         * @description One row of ``GET /api/samples`` — deliberately lighter than
         *     `SampleDetailOut`: no current result, no certificate list, so listing a
         *     hundred samples costs one query, not a hundred and one.
         */
        SampleListItemOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** Client Name */
            client_name: string;
            /** Submission Number */
            submission_number: string;
        };
        /** SampleOut */
        SampleOut: {
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** Drill Hole Id */
            drill_hole_id: number | null;
            /** From Depth M */
            from_depth_m: string | null;
            /** To Depth M */
            to_depth_m: string | null;
        };
        /**
         * SampleStatus
         * @description Where a sample is in its life at the lab.
         *
         *     Progression is Received → InPrep → ReadyForAssay → InAssay → Assayed →
         *     Reported. Rejected is terminal and reachable from anywhere before Assayed,
         *     because a sample can be found unusable at any bench. The legal moves live in
         *     :mod:`msa_lims.domain.lifecycle`, not here — an enum that also knows the
         *     transitions becomes the place every rule accidentally lands.
         * @enum {string}
         */
        SampleStatus: "received" | "in_prep" | "ready_for_assay" | "in_assay" | "assayed" | "reported" | "rejected";
        /**
         * SampleStatusUpdate
         * @description A bare lifecycle move — see ``sample_lifecycle/service.py``.
         *
         *     ``target`` is deliberately narrower than the full ``SampleStatus``
         *     vocabulary: ``in_assay``, ``assayed``, and ``reported`` are each reached
         *     only by the write path that produces the record making them true
         *     (charging a crucible, entering a result, issuing a certificate), never by
         *     a bare status flip here. Naming one of those is refused at this layer,
         *     before the request even reaches the service.
         */
        SampleStatusUpdate: {
            /**
             * Target
             * @enum {string}
             */
            target: "in_prep" | "ready_for_assay" | "rejected";
            /**
             * Reason
             * @description Required for rejecting a sample or returning one for re-assay.
             */
            reason?: string | null;
        };
        /**
         * SampleType
         * @description What physically arrived at the lab.
         *
         *     The distinction is not cosmetic. A core sample has a depth interval and
         *     belongs to a drill hole; a stream sediment has coordinates and belongs to
         *     nothing. A pulp arrives already prepared and skips the crushing stages
         *     entirely, which is why the prep workflow branches on this.
         * @enum {string}
         */
        SampleType: "core" | "rc_chip" | "soil" | "stream_sediment" | "rock_chip" | "pulp";
        /**
         * SolutionFinishCreate
         * @description An AAS or ICP-MS finish. Separate from :class:`FireAssayResultCreate`
         *     because the two finishes measure different things — there is no field in
         *     common beyond the sample, the portion, and the supersession pair.
         */
        SolutionFinishCreate: {
            /** Sample Id */
            sample_id: number;
            /**
             * Method
             * @description Which instrument read the dissolved bead. The gravimetric finish is excluded here at the schema layer: it weighs a bead rather than reading a solution, and has its own endpoint.
             * @enum {string}
             */
            method: "fire_assay_aas" | "fire_assay_icp_ms";
            /**
             * Concentration
             * @description What the instrument read, in concentration_unit.
             */
            concentration: number | string;
            /**
             * Concentration Unit
             * @description Must measure mass concentration. 'ppm' is deliberately not offered: on an instrument printout it is ambiguous between ug/mL of solution and ug/g of sample, and those differ by exactly the factor this calculation applies.
             * @enum {string}
             */
            concentration_unit: "mg/L" | "ug/L";
            /**
             * Solution Volume Ml
             * @description The volume the dissolved bead was made up to.
             */
            solution_volume_ml: number | string;
            /**
             * Sample Weight G
             * @description The portion assayed. Required unless crucible_id names the crucible the sample was charged into — then its recorded charge is used and this must be left unset.
             */
            sample_weight_g?: number | string | null;
            /**
             * Analysed At
             * Format: date-time
             * @description When the instrument read it, not when it was entered.
             */
            analysed_at: string;
            /**
             * Detection Limit
             * @description The method's detection limit, in concentration_unit.
             */
            detection_limit?: number | string | null;
            /**
             * Upper Calibration Limit
             * @description The method's top standard, in concentration_unit. A reading above it is refused rather than stored: past the top standard the instrument is extrapolating, so the number is not a measurement. Not stored on the row.
             */
            upper_calibration_limit?: number | string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Supersedes Id
             * @description Set to correct an existing result.
             */
            supersedes_id?: number | null;
            /**
             * Superseded Reason
             * @description Required when supersedes_id is set.
             */
            superseded_reason?: string | null;
            /**
             * Crucible Id
             * @description The crucible this assay came from; its recorded charge is derived as the portion weight.
             */
            crucible_id?: number | null;
        };
        /** SubmissionCreate */
        SubmissionCreate: {
            /** Client Id */
            client_id: number;
            /** Project Id */
            project_id?: number | null;
            /** Client Reference */
            client_reference?: string | null;
            /** Purchase Order */
            purchase_order?: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Declared Sample Count */
            declared_sample_count?: number | null;
            /**
             * Rush
             * @default false
             */
            rush: boolean;
            /** Requested Tat Days */
            requested_tat_days?: number | null;
            /** Comments */
            comments?: string | null;
            /** Samples */
            samples: components["schemas"]["SampleCreate"][];
        };
        /** SubmissionOut */
        SubmissionOut: {
            /** Id */
            id: number;
            /** Submission Number */
            submission_number: string;
            /** Client Id */
            client_id: number;
            /** Project Id */
            project_id: number | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Declared Sample Count */
            declared_sample_count: number | null;
            /** Samples */
            samples: components["schemas"]["SampleOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    whoami_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_clients_api_clients_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_drill_hole_api_drill_holes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillHoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillHoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fire_assay_result_api_fire_assay_results_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FireAssayResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireAssayResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_solution_finish_api_fire_assay_results_solution_finish_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolutionFinishCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireAssayResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_certificate_api_certificates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_certificate_api_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_certificate_pdf_api_certificates__certificate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_samples_api_samples_get: {
        parameters: {
            query?: {
                client_id?: number | null;
                status?: components["schemas"]["SampleStatus"] | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sample_api_samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sample_provenance_api_samples__sample_id__provenance_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_sample_status_api_samples__sample_id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_submissions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_flux_recipes_api_flux_recipes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluxRecipeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flux_recipe_api_flux_recipes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FluxRecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluxRecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_batches_api_batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_crucible_api_batches__batch_id__crucibles_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrucibleChargeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_crucible_parting_api_batches__batch_id__crucibles__crucible_id__parting_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
                crucible_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CruciblePartingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_crucible_weighing_api_batches__batch_id__crucibles__crucible_id__weighing_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
                crucible_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrucibleWeighingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_batch_status_api_batches__batch_id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_batch_qc_dossier_api_batches__batch_id__qc_dossier_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcDossierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_qc_materials_api_qc_materials_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcMaterialOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_qc_material_api_qc_materials_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QcMaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcMaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_audit_chain_verification_api_audit_verify_get: {
        parameters: {
            query?: {
                upto?: number | null;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditChainVerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_multi_element_results_api_samples__sample_id__multi_element_results_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiElementResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_multi_element_results_api_samples__sample_id__multi_element_results_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MultiElementImportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiElementImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
