/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Batches */
        get: operations["read_batches_api_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Batch */
        get: operations["read_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Charge Crucible */
        post: operations["charge_crucible_api_batches__batch_id__crucibles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles/{crucible_id}/parting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Crucible Parting */
        post: operations["record_crucible_parting_api_batches__batch_id__crucibles__crucible_id__parting_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/crucibles/{crucible_id}/weighing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Crucible Weighing */
        post: operations["record_crucible_weighing_api_batches__batch_id__crucibles__crucible_id__weighing_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance Batch Status */
        patch: operations["advance_batch_status_api_batches__batch_id__status_patch"];
        trace?: never;
    };
    "/api/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Certificate */
        post: operations["create_certificate_api_certificates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Certificate */
        get: operations["read_certificate_api_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the signed Certificate of Analysis */
        get: operations["download_certificate_pdf_api_certificates__certificate_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Client */
        post: operations["create_client_api_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drill-holes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Drill Hole */
        post: operations["create_drill_hole_api_drill_holes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fire-assay-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fire Assay Result */
        post: operations["create_fire_assay_result_api_fire_assay_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flux-recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Flux Recipes */
        get: operations["read_flux_recipes_api_flux_recipes_get"];
        put?: never;
        /** Create Flux Recipe */
        post: operations["create_flux_recipe_api_flux_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qc-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Qc Materials */
        get: operations["read_qc_materials_api_qc_materials_get"];
        put?: never;
        /** Create Qc Material */
        post: operations["create_qc_material_api_qc_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Samples */
        get: operations["read_samples_api_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Sample */
        get: operations["read_sample_api_samples__sample_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/samples/{sample_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance Sample Status */
        patch: operations["advance_sample_status_api_samples__sample_id__status_patch"];
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Submission
         * @description Register a work order and the sample rows that arrived with it.
         *
         *     ``actor`` and ``received_by`` are resolved from the same request and
         *     normally agree, but the role check reads ``actor.role`` — never
         *     ``received_by.role`` — so authorisation always reflects what the current
         *     caller holds right now, not whatever :class:`~msa_lims.db.models.LabUser`
         *     row last recorded.
         */
        post: operations["create_submission_api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchCreate */
        BatchCreate: {
            /** Notes */
            notes?: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
        /** BatchDetailOut */
        BatchDetailOut: {
            /** Batch Number */
            batch_number: string;
            /** Crucibles */
            crucibles: components["schemas"]["CrucibleSlotOut"][];
            /** Furnace Columns */
            furnace_columns: number;
            /** Furnace Rows */
            furnace_rows: number;
            /** Id */
            id: number;
            /** Notes */
            notes: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By Id */
            opened_by_id: number;
            /** Status */
            status: string;
        };
        /** BatchOut */
        BatchOut: {
            /** Batch Number */
            batch_number: string;
            /** Id */
            id: number;
            /** Notes */
            notes: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Opened By Id */
            opened_by_id: number;
            /** Status */
            status: string;
        };
        /**
         * BatchStatus
         * @description Where a fire assay batch is in the furnace cycle.
         *
         *     These are physical states of a tray of crucibles, not workflow conveniences:
         *     once a batch is InFusion it is inside a 1000 °C furnace and nothing about it
         *     can be edited.
         * @enum {string}
         */
        BatchStatus: "pending" | "charging" | "in_fusion" | "fused" | "in_cupellation" | "cupelled" | "completed";
        /** BatchStatusUpdate */
        BatchStatusUpdate: {
            status: components["schemas"]["BatchStatus"];
        };
        /** CertificateCreate */
        CertificateCreate: {
            /** Client Id */
            client_id: number;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Notes */
            notes?: string | null;
            /** Sample Ids */
            sample_ids: number[];
            /**
             * Superseded Reason
             * @description Required when supersedes_id is set.
             */
            superseded_reason?: string | null;
            /**
             * Supersedes Id
             * @description Set to amend an existing certificate.
             */
            supersedes_id?: number | null;
        };
        /** CertificateOut */
        CertificateOut: {
            /** Certificate Number */
            certificate_number: string;
            /** Client Id */
            client_id: number;
            /** Id */
            id: number;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Issued By Id */
            issued_by_id: number;
            /** Notes */
            notes: string | null;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Samples */
            samples: components["schemas"]["CertifiedSampleOut"][];
            /** Superseded Reason */
            superseded_reason: string | null;
            /** Supersedes Id */
            supersedes_id: number | null;
        };
        /**
         * CertificateReferenceOut
         * @description One certificate that names a sample — not the whole document, just
         *     enough to link to it via ``GET /api/certificates/{id}``.
         */
        CertificateReferenceOut: {
            /** Certificate Number */
            certificate_number: string;
            /** Id */
            id: number;
        };
        /**
         * CertifiedSampleOut
         * @description One sample a certificate covers, and the specific result it certified —
         *     see ``certificates/service.py``'s ``CertifiedSampleInfo`` for why this is
         *     the frozen-at-issuance result, not necessarily the sample's current one.
         */
        CertifiedSampleOut: {
            au: components["schemas"]["MeasuredValueOut"];
            /** Fire Assay Result Id */
            fire_assay_result_id: number;
            /** Method */
            method: string;
            /** Sample Id */
            sample_id: number;
            /** Sample Label */
            sample_label: string;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Billing Address */
            billing_address?: string | null;
            /**
             * Code
             * @description e.g. 'MSA'
             */
            code: string;
            /** Contact Person */
            contact_person?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
        };
        /** ClientOut */
        ClientOut: {
            /** Billing Address */
            billing_address: string | null;
            /** Code */
            code: string;
            /** Contact Person */
            contact_person: string | null;
            /** Email */
            email: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable" | "not_configured";
        };
        /** CrucibleChargeCreate */
        CrucibleChargeCreate: {
            /**
             * Charged At
             * Format: date-time
             */
            charged_at: string;
            /** Flux Recipe Id */
            flux_recipe_id: number;
            /** Notes */
            notes?: string | null;
            /** Position Col */
            position_col: number;
            /** Position Row */
            position_row: number;
            /** Qc Material Id */
            qc_material_id?: number | null;
            /** Sample Id */
            sample_id?: number | null;
            /** Sample Weight G */
            sample_weight_g: number | string;
        };
        /** CrucibleOut */
        CrucibleOut: {
            /** Batch Id */
            batch_id: number;
            /** Borax G */
            borax_g: string;
            /**
             * Charged At
             * Format: date-time
             */
            charged_at: string;
            /** Flour G */
            flour_g: string;
            /** Flux Recipe Id */
            flux_recipe_id: number;
            /** Gold Bead Mg */
            gold_bead_mg: string | null;
            /** Id */
            id: number;
            /** Lead Button Weight Mg */
            lead_button_weight_mg: string | null;
            /** Litharge G */
            litharge_g: string;
            /** Nitre G */
            nitre_g: string;
            /** Notes */
            notes: string | null;
            /** Parted At */
            parted_at: string | null;
            /** Parting Acid Volume Ml */
            parting_acid_volume_ml: string | null;
            /** Position Col */
            position_col: number;
            /** Position Row */
            position_row: number;
            /** Prill Weight Mg */
            prill_weight_mg: string | null;
            /** Qc Material Id */
            qc_material_id: number | null;
            /** Sample Id */
            sample_id: number | null;
            /** Sample Weight G */
            sample_weight_g: string;
            /** Silica G */
            silica_g: string;
            /** Soda Ash G */
            soda_ash_g: string;
            /** Status */
            status: string;
            /** Weighed At */
            weighed_at: string | null;
        };
        /**
         * CruciblePartingCreate
         * @description The measurements taken while parting one cupelled crucible.
         */
        CruciblePartingCreate: {
            /**
             * Lead Button Weight Mg
             * @description Lead button from the fusion.
             */
            lead_button_weight_mg: number | string;
            /**
             * Parted At
             * Format: date-time
             * @description When the parting happened, not when it was entered.
             */
            parted_at: string;
            /**
             * Parting Acid Volume Ml
             * @description Acid used to part the prill.
             */
            parting_acid_volume_ml: number | string;
            /**
             * Prill Weight Mg
             * @description Doré bead left by cupellation.
             */
            prill_weight_mg: number | string;
        };
        /**
         * CrucibleSlotOut
         * @description One crucible as it appears in a batch's tray — lean, unlike
         *     `CrucibleOut`: a grid of up to 36 of these needs a position, a status to
         *     colour it, and whatever it holds' label, not every flux amount and
         *     measurement column. That fuller detail is one click away at the sample
         *     it names; nothing here needs its own crucible-detail endpoint yet.
         */
        CrucibleSlotOut: {
            /** Id */
            id: number;
            /** Position Col */
            position_col: number;
            /** Position Row */
            position_row: number;
            /** Qc Material Id */
            qc_material_id: number | null;
            /** Qc Material Name */
            qc_material_name: string | null;
            /** Qc Material Type */
            qc_material_type: string | null;
            /** Sample Id */
            sample_id: number | null;
            /** Sample Label */
            sample_label: string | null;
            /** Status */
            status: string;
        };
        /**
         * CrucibleWeighingCreate
         * @description The final gold-bead weighing for one parted crucible.
         */
        CrucibleWeighingCreate: {
            /**
             * Gold Bead Mg
             * @description Gold alone, after parting.
             */
            gold_bead_mg: number | string;
            /**
             * Weighed At
             * Format: date-time
             * @description When the weighing happened, not when entered.
             */
            weighed_at: string;
        };
        /** DrillHoleCreate */
        DrillHoleCreate: {
            /** Azimuth Degrees */
            azimuth_degrees?: number | string | null;
            /** Dip Degrees */
            dip_degrees?: number | string | null;
            /** Drilling Method */
            drilling_method?: string | null;
            /** Easting */
            easting?: number | string | null;
            /** Elevation M */
            elevation_m?: number | string | null;
            /**
             * Hole Id
             * @description e.g. 'MSA-24-001'
             */
            hole_id: string;
            /** Northing */
            northing?: number | string | null;
            /** Project Id */
            project_id: number;
            /** Total Depth M */
            total_depth_m?: number | string | null;
            /** Utm Zone */
            utm_zone?: string | null;
        };
        /** DrillHoleOut */
        DrillHoleOut: {
            /** Azimuth Degrees */
            azimuth_degrees: string | null;
            /** Dip Degrees */
            dip_degrees: string | null;
            /** Drilling Method */
            drilling_method: string | null;
            /** Easting */
            easting: string | null;
            /** Elevation M */
            elevation_m: string | null;
            /** Hole Id */
            hole_id: string;
            /** Id */
            id: number;
            /** Northing */
            northing: string | null;
            /** Project Id */
            project_id: number;
            /** Total Depth M */
            total_depth_m: string | null;
            /** Utm Zone */
            utm_zone: string | null;
        };
        /** FireAssayResultCreate */
        FireAssayResultCreate: {
            /**
             * Analysed At
             * Format: date-time
             * @description When the weighing happened, not when it was entered.
             */
            analysed_at: string;
            /** Balance Sensitivity Mg */
            balance_sensitivity_mg?: number | string | null;
            /**
             * Crucible Id
             * @description The crucible this assay came from; its recorded charge is derived as the portion weight.
             */
            crucible_id?: number | null;
            /**
             * Gold Bead Mg
             * @description Bead weight after parting — gold alone. Required unless crucible_id names a crucible that has been weighed; then its recorded bead is used and this must be left unset.
             */
            gold_bead_mg?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Sample Id */
            sample_id: number;
            /**
             * Sample Weight G
             * @description The portion assayed. Required unless crucible_id names the crucible the sample was charged into — then its recorded charge is used and this must be left unset.
             */
            sample_weight_g?: number | string | null;
            /**
             * Superseded Reason
             * @description Required when supersedes_id is set.
             */
            superseded_reason?: string | null;
            /**
             * Supersedes Id
             * @description Set to correct an existing result.
             */
            supersedes_id?: number | null;
        };
        /** FireAssayResultOut */
        FireAssayResultOut: {
            /**
             * Analysed At
             * Format: date-time
             */
            analysed_at: string;
            au: components["schemas"]["MeasuredValueOut"];
            /** Balance Sensitivity Mg */
            balance_sensitivity_mg: string | null;
            /** Crucible Id */
            crucible_id: number | null;
            /** Gold Bead Mg */
            gold_bead_mg: string;
            /** Id */
            id: number;
            /** Method */
            method: string;
            /** Notes */
            notes: string | null;
            /** Sample Id */
            sample_id: number;
            /** Sample Weight G */
            sample_weight_g: string;
            /** Superseded Reason */
            superseded_reason: string | null;
            /** Supersedes Id */
            supersedes_id: number | null;
        };
        /** FluxRecipeCreate */
        FluxRecipeCreate: {
            /** Borax G */
            borax_g: number | string;
            /** Flour G */
            flour_g: number | string;
            /** Litharge G */
            litharge_g: number | string;
            matrix_type: components["schemas"]["MatrixType"];
            /**
             * Name
             * @description e.g. 'Standard Silicate'
             */
            name: string;
            /** Nitre G */
            nitre_g: number | string;
            /**
             * Nominal Portion G
             * @description Sample weight this recipe's amounts are calibrated for.
             */
            nominal_portion_g: number | string;
            /** Silica G */
            silica_g: number | string;
            /** Soda Ash G */
            soda_ash_g: number | string;
        };
        /** FluxRecipeOut */
        FluxRecipeOut: {
            /** Borax G */
            borax_g: string;
            /** Flour G */
            flour_g: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Litharge G */
            litharge_g: string;
            /** Matrix Type */
            matrix_type: string;
            /** Name */
            name: string;
            /** Nitre G */
            nitre_g: string;
            /** Nominal Portion G */
            nominal_portion_g: string;
            /** Silica G */
            silica_g: string;
            /** Soda Ash G */
            soda_ash_g: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            database: components["schemas"]["ComponentHealth"];
            qc_sentinel: components["schemas"]["ComponentHealth"];
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** Version */
            version: string;
        };
        /**
         * MatrixType
         * @description The mineralogical character of a sample charge — what it is made of,
         *     for the purpose of choosing a flux.
         *
         *     Independent of :class:`SampleType`, which classifies the physical medium
         *     a sample arrived as (core, soil, pulp, ...). A silicate-hosted soil and a
         *     silicate-hosted core take the same flux; a sulfide-rich core and an
         *     oxide-rich core do not, despite both being "core." Nothing in this schema
         *     infers a matrix from a sample type or a lithology code — a technician
         *     assigns it when charging a crucible, the same way they would read it off
         *     a geologist's log.
         * @enum {string}
         */
        MatrixType: "silicate" | "sulfide" | "oxide" | "carbonate" | "carbonaceous";
        /**
         * MeasuredValueOut
         * @description Mirrors ``frontend/src/types.ts``'s ``MeasuredValue`` exactly, so the
         *     same ``formatMeasured`` helper renders a non-detect correctly the moment
         *     a screen exists to show one — a censored value is never a null string
         *     quietly standing in for zero.
         */
        MeasuredValueOut: {
            /** Censored */
            censored: boolean;
            /** Detection Limit */
            detection_limit: string | null;
            /** Unit */
            unit: string;
            /** Value */
            value: string | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Client Id */
            client_id: number;
            /** Description */
            description?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Start Date */
            start_date?: string | null;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Client Id */
            client_id: number;
            /** Description */
            description: string | null;
            /** End Date */
            end_date: string | null;
            /** Id */
            id: number;
            /** Location */
            location: string | null;
            /** Name */
            name: string;
            /** Start Date */
            start_date: string | null;
        };
        /** QcMaterialCreate */
        QcMaterialCreate: {
            /** Certified Au Uncertainty G T */
            certified_au_uncertainty_g_t?: number | string | null;
            /** Certified Au Value G T */
            certified_au_value_g_t?: number | string | null;
            /** Lot Number */
            lot_number?: string | null;
            /**
             * Name
             * @description e.g. 'OREAS 501d'
             */
            name: string;
            /** Notes */
            notes?: string | null;
            qc_type: components["schemas"]["QcMaterialType"];
        };
        /** QcMaterialOut */
        QcMaterialOut: {
            /** Certified Au Uncertainty G T */
            certified_au_uncertainty_g_t: string | null;
            /** Certified Au Value G T */
            certified_au_value_g_t: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Lot Number */
            lot_number: string | null;
            /** Name */
            name: string;
            /** Qc Type */
            qc_type: string;
        };
        /**
         * QcMaterialType
         * @description What kind of control was inserted into a batch.
         *
         *     The LIMS records the *insertion* — which material went into which position.
         *     Judging the result is QC Sentinel's job; there is deliberately no verdict
         *     vocabulary in this system.
         * @enum {string}
         */
        QcMaterialType: "crm" | "blank" | "coarse_blank" | "field_duplicate" | "prep_duplicate" | "pulp_duplicate";
        /** SampleCreate */
        SampleCreate: {
            /** Alteration Code */
            alteration_code?: string | null;
            /** Comments */
            comments?: string | null;
            /** Easting */
            easting?: number | string | null;
            /** Elevation M */
            elevation_m?: number | string | null;
            /** Lithology Code */
            lithology_code?: string | null;
            /** Northing */
            northing?: number | string | null;
            /**
             * Sample Id
             * @description e.g. 'MSA-24-001-142.50_144.00' (drill) or 'MSA-24-SO-00417' (surface)
             */
            sample_id: string;
            sample_type: components["schemas"]["SampleType"];
            /** Weight Received G */
            weight_received_g?: number | string | null;
        };
        /** SampleDetailOut */
        SampleDetailOut: {
            /** Certificates */
            certificates: components["schemas"]["CertificateReferenceOut"][];
            current_result: components["schemas"]["FireAssayResultOut"] | null;
            /** Drill Hole Id */
            drill_hole_id: number | null;
            /** From Depth M */
            from_depth_m: string | null;
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** Submission Id */
            submission_id: number;
            /** To Depth M */
            to_depth_m: string | null;
        };
        /**
         * SampleListItemOut
         * @description One row of ``GET /api/samples`` — deliberately lighter than
         *     `SampleDetailOut`: no current result, no certificate list, so listing a
         *     hundred samples costs one query, not a hundred and one.
         */
        SampleListItemOut: {
            /** Client Name */
            client_name: string;
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** Submission Number */
            submission_number: string;
        };
        /** SampleOut */
        SampleOut: {
            /** Drill Hole Id */
            drill_hole_id: number | null;
            /** From Depth M */
            from_depth_m: string | null;
            /** Id */
            id: number;
            /** Sample Id */
            sample_id: string;
            /** Sample Type */
            sample_type: string;
            /** Status */
            status: string;
            /** To Depth M */
            to_depth_m: string | null;
        };
        /**
         * SampleStatus
         * @description Where a sample is in its life at the lab.
         *
         *     Progression is Received → InPrep → ReadyForAssay → InAssay → Assayed →
         *     Reported. Rejected is terminal and reachable from anywhere before Assayed,
         *     because a sample can be found unusable at any bench. The legal moves live in
         *     :mod:`msa_lims.domain.lifecycle`, not here — an enum that also knows the
         *     transitions becomes the place every rule accidentally lands.
         * @enum {string}
         */
        SampleStatus: "received" | "in_prep" | "ready_for_assay" | "in_assay" | "assayed" | "reported" | "rejected";
        /**
         * SampleStatusUpdate
         * @description A bare lifecycle move — see ``sample_lifecycle/service.py``.
         *
         *     ``target`` is deliberately narrower than the full ``SampleStatus``
         *     vocabulary: ``in_assay``, ``assayed``, and ``reported`` are each reached
         *     only by the write path that produces the record making them true
         *     (charging a crucible, entering a result, issuing a certificate), never by
         *     a bare status flip here. Naming one of those is refused at this layer,
         *     before the request even reaches the service.
         */
        SampleStatusUpdate: {
            /**
             * Reason
             * @description Required for rejecting a sample or returning one for re-assay.
             */
            reason?: string | null;
            /**
             * Target
             * @enum {string}
             */
            target: "in_prep" | "ready_for_assay" | "rejected";
        };
        /**
         * SampleType
         * @description What physically arrived at the lab.
         *
         *     The distinction is not cosmetic. A core sample has a depth interval and
         *     belongs to a drill hole; a stream sediment has coordinates and belongs to
         *     nothing. A pulp arrives already prepared and skips the crushing stages
         *     entirely, which is why the prep workflow branches on this.
         * @enum {string}
         */
        SampleType: "core" | "rc_chip" | "soil" | "stream_sediment" | "rock_chip" | "pulp";
        /** SubmissionCreate */
        SubmissionCreate: {
            /** Client Id */
            client_id: number;
            /** Client Reference */
            client_reference?: string | null;
            /** Comments */
            comments?: string | null;
            /** Declared Sample Count */
            declared_sample_count?: number | null;
            /** Project Id */
            project_id?: number | null;
            /** Purchase Order */
            purchase_order?: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Requested Tat Days */
            requested_tat_days?: number | null;
            /**
             * Rush
             * @default false
             */
            rush: boolean;
            /** Samples */
            samples: components["schemas"]["SampleCreate"][];
        };
        /** SubmissionOut */
        SubmissionOut: {
            /** Client Id */
            client_id: number;
            /** Declared Sample Count */
            declared_sample_count: number | null;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Samples */
            samples: components["schemas"]["SampleOut"][];
            /** Submission Number */
            submission_number: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_batches_api_batches_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_crucible_api_batches__batch_id__crucibles_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrucibleChargeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_crucible_parting_api_batches__batch_id__crucibles__crucible_id__parting_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
                crucible_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CruciblePartingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_crucible_weighing_api_batches__batch_id__crucibles__crucible_id__weighing_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
                crucible_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrucibleWeighingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrucibleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_batch_status_api_batches__batch_id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_certificate_api_certificates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CertificateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_certificate_api_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_certificate_pdf_api_certificates__certificate_id__pdf_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                certificate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_clients_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_drill_hole_api_drill_holes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrillHoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrillHoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fire_assay_result_api_fire_assay_results_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FireAssayResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FireAssayResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_flux_recipes_api_flux_recipes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluxRecipeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flux_recipe_api_flux_recipes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FluxRecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FluxRecipeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_qc_materials_api_qc_materials_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcMaterialOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_qc_material_api_qc_materials_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QcMaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QcMaterialOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_samples_api_samples_get: {
        parameters: {
            query?: {
                client_id?: number | null;
                status?: components["schemas"]["SampleStatus"] | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleListItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_sample_api_samples__sample_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_sample_status_api_samples__sample_id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path: {
                sample_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_submissions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-actor"?: string | null;
                "x-actor-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
